version: '2'
services:
  'mariadb':
    image: mariadb
    ports:
     - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_USER: coffee-recipe
      MYSQL_PASSWORD: coffee
      MYSQL_DATABASE: coffee-recipe
  'mqtt':
    image: toke/mosquitto
    ports:
     - "1813:1813"
  'coffee-recipe':
    image: container-registry.synyx.de/coffee-recipe
    volumes:
      - ./docker/coffee-recipe/application.properties:/application.properties
    links:
      - mqtt:mqtt.synyx.coffee
      - mariadb:mariadb.synyx.coffee
    depends_on:
      - mqtt
      - mariadb
